### ISSUE TITLE
Can't add 25 and 475

### ISSUE THREAD

**Issue by wizzwizz4** [lduck11007/claculator#1]
I really want to solve the answer to this prolbem, but your claculator doesn't do it. I will post a bad review on Ylep.

**Comment by leowhitehead** [comment]
Thanks for mentioning this. While I do want my claculator to be able to add as many numbers together as possible, reasonably, there is a limitation to how many different numbers it can do so to. In 25mb of code, this program accounts for 480000 combinations of numbers, but I don't believe that 25 and 475 are one of them. In classical computing, owing to Moore's law there is a limit to what can be calculated with classical computations, and it seems that adding 25 and 475 is one of those limitations. Hopefully with the inevitable advent of quantum computing, we will finally be able to add 25 and 475.

**Comment by GabrielRRussell** [comment]
@wizzwizz4 Please consider taking a look at my brand new pull request. I've fixed the issue you've been asking for a solution to. It's already hosted on my personal fork of claculator, but you may find it userful to wait for it to be integrated into the main Project. Check out [Pull Request #2](https://github.com/lduck11007/claculator/pull/2/commits/d029a5b73c12286d9c0f6b4ade1c71c91cfe55af)

Using some impeccably intelligent optimizations, I've been able to condense the operations into a mere few lines of code. Moore's Law does not dictate processing speed, yet only transistor count. Thanks to the new transistor count of modern processors, it is possible to tightly pack these operations together.

Thank you for using claculator.

**Comment by leowhitehead** [comment]
I've merged @GabrielRRussell's pull request, Claculator should now be able to add 25 and 475 without problems.
